app/menu_types/__init__.py
from flask import Blueprint

menu_types_bp = Blueprint('menu_types_bp', __name__, 
                          template_folder='templates', 
                          static_folder='static')

from . import views

app/menu_types/views.py
from . import menu_types_bp
from app.extensions import db
from app.models.stores import Store
from app.models.menu_types import Menu_type
from app.utils import check_login_in
from flask import render_template, redirect, url_for, request


@menu_types_bp.route('/store/<int:store_id>/menu_types')
@check_login_in()
def index(store_id):
    menu_types = Menu_type.query.filter_by(store_id=store_id).order_by(Menu_type.id).all()

    return render_template("menu_types/index.html", menu_types=menu_types, store_id=store_id)


@menu_types_bp.route('/store/<int:store_id>/menu_type/new')
@check_login_in()
def new(store_id):
    store = Store.query.get(store_id)

    return render_template("menu_types/new.html", store=store)


@menu_types_bp.route('/store/<int:store_id>/menu_type/create', methods=['POST'])
@check_login_in()
def create(store_id):
    store = Store.query.get(store_id)
    name = request.form['name']

    menu_type = Menu_type(name=name, store=store)
    db.session.add(menu_type)
    db.session.commit()

    return redirect(url_for('menu_types_bp.index', store_id=store_id))


@menu_types_bp.route('/menu_type/<int:id>/edit')
@check_login_in()
def edit(id):
    menu_type = Menu_type.query.get(id)

    return render_template('menu_types/edit.html', menu_type=menu_type)


@menu_types_bp.route('/menu_type/<int:id>/update', methods=['POST'])
@check_login_in()
def update(id):
    menu_type = Menu_type.query.get(id)

    menu_type.name = request.form['name']
    db.session.commit()

    return redirect(url_for('menu_types_bp.index', store_id=menu_type.store_id))


@menu_types_bp.route('/menu_type/<int:id>/delete')
@check_login_in()
def delete(id):
    menu_type = Menu_type.query.get(id)

    db.session.delete(menu_type)
    db.session.commit()

    return redirect(url_for('menu_types_bp.index', store_id=menu_type.store_id))

app/templates/menu_types/edit.html
{% extends "header.html" %}

{% block body %}
<h1>編輯菜單類別</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('menu_types_bp.update', id=menu_type.id) }}">
    <div class="form-group">
      <label for="name">名稱</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ menu_type.name }}"/>
    </div>

    <button type="submit" class="btn btn-primary">編輯</button>
  </form>
</div>
{% endblock %}

app/templates/menu_types/index.html
{% extends "header.html" %} 

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('stores_bp.index') }}">Stores</a></li>
          <li class="breadcrumb-item active" aria-current="page">Menu_types</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-12">
      <a href="{{ url_for('menu_types_bp.new', store_id=store_id) }}" class="btn btn-info">新增菜單類別</a>
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <tr>
            <th>菜單類別</th>
            <th>菜品新增</th>
            <th>菜品列表</th>
            <th>編輯</th>
          </tr>
        </thead>
        <tbody>
          {% for menu_type in menu_types %}
          <tr>
            <td>{{ menu_type.name }}</td>
            <td>
              <a href="{{ url_for('menus_bp.new', menu_type_id=menu_type.id) }}" class="btn btn-info">新增菜品</a>
            </td>
            <td>
              <a href="{{ url_for('menus_bp.index', menu_type_id=menu_type.id) }}" class="btn btn-info">連結</a>
            </td>
            <td>
              <a href="{{ url_for('menu_types_bp.edit', id=menu_type.id) }}" class="btn btn-info">修改</a>
              <a href="{{ url_for('menu_types_bp.delete', id=menu_type.id) }}" class="btn btn-danger" onclick="return confirm('確定刪除該菜單類別？')">刪除</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

app/templates/menu_types/new.html
{% extends "header.html" %}

{% block body %}
<h1>新增菜單類別</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('menu_types_bp.create', store_id=store.id) }}">
    <div class="form-group">
      <label for="name">菜單類別</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="菜單類別"/>
    </div>

    <button type="submit" class="btn btn-primary">新增</button>
  </form>
</div>
{% endblock %}