app/models/menu_types.py
from datetime import datetime
from app.extensions import db

class Menu_type(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(50), unique=True, nullable=False)

    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    store_id = db.Column(db.Integer, db.ForeignKey('store.id'), nullable=False)
    store = db.relationship('Store', back_populates="menu_types")

    def __init__(self, name, store):
        self.name = name
        self.store = store

app/menus/__init__.py
from flask import Blueprint

menus_bp = Blueprint('menus_bp', __name__, template_folder='templates', static_folder='static')

from . import views

app/menus/views.py
import os, uuid, shutil, boto3
from . import menus_bp
from app.models.menu_types import Menu_type
from app.utils import check_login_in
from sqlalchemy import create_engine, text
from flask import render_template, redirect, url_for, request, current_app, session

engine = create_engine(os.getenv('DATABASE_URL').replace("postgres:", "postgresql:"))

s3_bucket_name = os.getenv('S3_BUCKET_NAME')
s3_region = os.getenv('S3_REGION')
s3 = boto3.resource("s3", 
                  aws_access_key_id = os.getenv('AMAZON_S3_ID'), 
                  aws_secret_access_key = os.getenv('AMAZON_S3_KEY')
                  )


@menus_bp.route('/menu_type/<int:menu_type_id>/menus')
@check_login_in()
def index(menu_type_id):
    menu_type = Menu_type.query.get(menu_type_id)

    user_id = session.get("id")
    sql_cmd = text(f"SELECT * FROM menu{user_id} WHERE menu_type_id = {menu_type_id} ORDER BY id")
    with engine.connect() as conn:
        menus = conn.execute(sql_cmd).fetchall()
        conn.commit()

    return render_template("menus/index.html", menus=menus, store_id=menu_type.store_id)


@menus_bp.route('/menu_type/<int:menu_type_id>/menu/new')
@check_login_in()
def new(menu_type_id):
    return render_template("menus/new.html", menu_type_id=menu_type_id)


@menus_bp.route('/menu_type/<int:menu_type_id>/menu/create', methods=['POST'])
@check_login_in()
def create(menu_type_id):
    user_id = session.get("id")
    name = request.form['name']
    description = request.form['description']
    price = request.form['price']
    img = request.files['img']

    sql_cmd = text(f"INSERT INTO menu{user_id} (name, description, price, menu_type_id) VALUES ('{name}', '{description}', '{price}', '{menu_type_id}') RETURNING id".replace("%", "%%"))

    with engine.connect() as conn:
        [menu_id] = conn.execute(sql_cmd).fetchone()
        conn.commit()

    if img.filename != '':
        # 上傳圖片到AWS S3
        new_filename = uuid.uuid4().hex + '.' + img.filename.rsplit('.', 1)[1].lower()
        s3.Bucket(s3_bucket_name).upload_fileobj(img, new_filename)

        # 把圖片路徑寫入Menu
        img_path = f"https://{s3_bucket_name}.s3.{s3_region}.amazonaws.com/{new_filename}"
        sql_cmd = text(f"UPDATE menu{user_id} SET img_path = '{img_path}' WHERE id = {menu_id}")

        with engine.connect() as conn:
            conn.execute(sql_cmd)
            conn.commit()

    return redirect(url_for('menus_bp.index', menu_type_id=menu_type_id))


@menus_bp.route('/menu/<int:id>/edit')
@check_login_in()
def edit(id):
    user_id = session.get("id")

    sql_cmd = text(f"SELECT * FROM menu{user_id} WHERE id = {id}")
    with engine.connect() as conn:
        menu = conn.execute(sql_cmd).fetchone()
        conn.commit()

    return render_template('menus/edit.html', menu=menu)


@menus_bp.route('/menu/<int:id>/update', methods=['POST'])
@check_login_in()
def update(id):
    user_id = session.get("id")
    name = request.form['name']
    description = request.form['description']
    price = request.form['price']
    img = request.files['img']

    sql_cmd = text(f"UPDATE menu{user_id} SET name = '{name}', description = '{description}', price = '{price}' WHERE id = {id} RETURNING id, menu_type_id".replace("%", "%%"))

    with engine.connect() as conn:
        [menu_id, menu_type_id] = conn.execute(sql_cmd).fetchone()
        conn.commit()

    if img.filename != '':
        # 上傳圖片到AWS S3
        new_filename = uuid.uuid4().hex + '.' + img.filename.rsplit('.', 1)[1].lower()
        s3.Bucket(s3_bucket_name).upload_fileobj(img, new_filename)

        # 把圖片路徑寫入Menu
        img_path = f"https://{s3_bucket_name}.s3.{s3_region}.amazonaws.com/{new_filename}"
        sql_cmd = text(f"UPDATE menu{user_id} SET img_path = '{img_path}' WHERE id = {menu_id}")

        with engine.connect() as conn:
            conn.execute(sql_cmd)
            conn.commit()

    return redirect(url_for('menus_bp.index', menu_type_id=menu_type_id))


@menus_bp.route('/menus/<int:id>/delete')
@check_login_in()
def delete(id):
    user_id = session.get("id")

    sql_cmd = text(f"DELETE FROM menu{user_id} WHERE id = {id} RETURNING menu_type_id")
    with engine.connect() as conn:
        [menu_type_id] = conn.execute(sql_cmd)
        conn.commit()

    return redirect(url_for('menus_bp.index', menu_type_id=menu_type_id[0]))


app/templates/menus/edit.html
{% extends "base.html" %}

{% block body %}
<h1>編輯菜品</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('menus_bp.update', id=menu.id) }}" enctype="multipart/form-data">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ menu.name }}"/>
    </div>

    <div class="form-group">
      <label for="description">Description</label>
      <input type="text" class="form-control" id="description" name="description" value="{{ menu.description }}"/>
    </div>

    <div class="form-group">
      <label for="price">Price</label>
      <input type="number" class="form-control" id="price" name="price" value="{{ menu.price }}" min="0"/>
    </div>

    <div class="form-group">
      <label for="img">Image</label>
      <input type="file" name="img" accept="image/*">
    </div>

    <button type="submit" class="btn btn-primary">編輯</button>
  </form>
</div>
{% endblock %}

app/templates/menus/index.html
{% extends "header.html" %} 

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('stores_bp.index') }}">Stores</a></li>
          <li class="breadcrumb-item"><a href="{{ url_for('menu_types_bp.index', store_id=store_id) }}">Menu_types</a></li>
          <li class="breadcrumb-item active" aria-current="page">Menus</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-12">
      <table class="table table-image">
        <thead>
          <tr>
            <th scope="col">名稱</th>
            <th scope="col">圖示</th>
            <th scope="col">價格</th>
            <th scope="col">介紹</th>
            <th scope="col">編輯</th>
          </tr>
        </thead>
        <tbody>
          {% for menu in menus %}
          <tr>
            <td scope="row">{{ menu.name }}</td>
            <td class="w-25">
                {% if menu.img_path != None %}
                <img class="card-img-top" src="{{ menu.img_path }}" alt="Card image cap">
                {% else %}
                <img class="card-img-top" src="#" alt="Card image cap">
                {% endif %}
            </td>
            <td>{{ menu.price }}</td>
            <td>{{ menu.description }}</td>
            <td>
              <a href="{{ url_for('menus_bp.edit', id=menu.id) }}" class="btn btn-info">修改</a>
              <a href="{{ url_for('menus_bp.delete', id=menu.id) }}" class="btn btn-danger" onclick="return confirm('確定刪除該菜品？')">刪除</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="row mt-5">
        <div class="col-12">
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/menus/new.html
{% extends "base.html" %}

{% block body %}
<h1>新增菜品</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('menus_bp.create', menu_type_id=menu_type_id) }}" enctype="multipart/form-data">
    <div class="form-group">
      <label for="name">名稱</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="name"/>
    </div>

    <div class="form-group">
      <label for="description">介紹</label>
      <input type="text" class="form-control" id="description" name="description" placeholder="description"/>
    </div>

    <div class="form-group">
      <label for="price">價格</label>
      <input type="number" class="form-control" id="price" name="price" placeholder=0 min="0"/>
    </div>

    <div class="form-group">
      <label for="img">圖示</label>
      <input type="file" name="img" accept="image/*">
    </div>

    <button type="submit" class="btn btn-primary">新增</button>
  </form>
</div>
{% endblock %}