app/models/stores.py
from datetime import datetime
from app.extensions import db

class Store(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    
    name = db.Column(db.String(20), unique=True, nullable=False)
    phone = db.Column(db.String(120), nullable=False)
    address = db.Column(db.Text, nullable=False)
    
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', back_populates="stores")
    menu_types = db.relationship('Menu_type', back_populates='store', cascade="all, delete")
    tables = db.relationship('Table', back_populates='store', cascade="all, delete")


    def __init__(self, name, phone, address, user):
        self.name = name
        self.phone = phone
        self.address = address
        self.user = user

app/stores/__init__.py
from flask import Blueprint

stores_bp = Blueprint('stores_bp', __name__, template_folder='templates', static_folder='static')

from . import views

app/stores/views.py
from . import stores_bp
from app.extensions import db
from app.models.users import User
from app.models.stores import Store
from app.utils import check_login_in
from flask import render_template, redirect, url_for, request, session


@stores_bp.route('/stores')
@check_login_in()
def index():
    user_id = session.get("id")

    user = User.query.filter_by(id=user_id).first()
    stores = Store.query.filter_by(user_id=user_id).order_by(Store.id).all()

    return render_template("stores/index.html", user=user, stores=stores)


@stores_bp.route('/store/new')
@check_login_in()
def new():
    return render_template("stores/new.html")


@stores_bp.route('/store/create', methods=['POST'])
@check_login_in()
def create():
    id = session.get("id")
    user = User.query.filter_by(id=id).first()

    name = request.form['name']
    phone = request.form['phone']
    address = request.form['address']

    store = Store(name=name, phone=phone, address=address, user=user)
    db.session.add(store)
    db.session.commit()

    return redirect(url_for('stores_bp.index'))


@stores_bp.route('/store/<int:id>/edit')
@check_login_in()
def edit(id):
    store = Store.query.get(id)

    return render_template('stores/edit.html', store=store)


@stores_bp.route('/store/<int:id>/update', methods=['POST'])
@check_login_in()
def update(id):
    store = Store.query.get(id)

    store.name = request.form['name']
    store.phone = request.form['phone']
    store.address = request.form['address']
    db.session.commit()

    return redirect(url_for('stores_bp.index'))


@stores_bp.route('/store/<int:id>/delete')
@check_login_in()
def delete(id):
    store = Store.query.get(id)

    db.session.delete(store)
    db.session.commit()

    return redirect(url_for('stores_bp.index'))

app/templates/stores/edit.html
{% extends "header.html" %}

{% block body %}
<h1>編輯餐廳</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('stores_bp.update', id=store.id) }}">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ store.name }}"/>
    </div>

    <div class="form-group">
      <label for="phone">phone</label>
      <input type="text" class="form-control" id="phone" name="phone" value="{{ store.phone }}"/>
    </div>

    <div class="form-group">
      <label for="address">address</label>
      <input type="text" class="form-control" id="address" name="address" value="{{ store.address }}"/>
    </div>

    <button type="submit" class="btn btn-primary">編輯</button>
  </form>
</div>
{% endblock %}

app/templates/stores/index.html
{% extends "header.html" %} 

{% block body %}
<a href="{{ url_for('stores_bp.new') }}" class="btn btn-info">新增餐廳</a>

<table class="table table-bordered table-striped">
  <thead class="thead-dark">
    <tr>
      <th>名稱</th>
      <th>電話</th>
      <th>地址</th>
      <th>菜單類別</th>
      <th>餐桌列表</th>
      <th>編輯</th>
    </tr>
  </thead>
  <tbody>
    {% for store in stores %}
    <tr>
      <td>{{ store.name }}</td>
      <td>{{ store.phone }}</td>
      <td>{{ store.address }}</td>
      <td>
        <a href="{{ url_for('menu_types_bp.index', store_id=store.id) }}" class="btn btn-info">連結</a>
      </td>
      <td>
        <a href="{{ url_for('tables_bp.index', store_id=store.id) }}" class="btn btn-info">連結</a>
      </td>
      <td>
        <a href="{{ url_for('stores_bp.edit', id=store.id) }}" class="btn btn-info">修改</a>
        <a href="{{ url_for('stores_bp.delete', id=store.id) }}" class="btn btn-danger" onclick="return confirm('確定刪除該餐廳？')">刪除</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/stores/new.html
{% extends "header.html" %}

{% block body %}
<h1>新增餐廳</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('stores_bp.create') }}">
    <div class="form-group">
      <label for="name">名稱</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="name"/>
    </div>

    <div class="form-group">
      <label for="phone">電話</label>
      <input type="text" class="form-control" id="phone" name="phone" placeholder="phone"/>
    </div>

    <div class="form-group">
      <label for="address">地址</label>
      <input type="text" class="form-control" id="address" name="address" placeholder="address"/>
    </div>

    <button type="submit" class="btn btn-primary">新增</button>
  </form>
</div>
{% endblock %}