app/tables/__init__.py
from flask import Blueprint

tables_bp = Blueprint('tables_bp', __name__, template_folder='templates', static_folder='static')

from . import views

app/tables/views.py
from . import tables_bp
from app import parameters
from app.extensions import db
from app.models.stores import Store
from app.models.tables import Table, TableState
from app.utils import check_login_in
from flask import render_template, redirect, url_for, request


@tables_bp.route('/store/<int:store_id>/tables')
@check_login_in()
def index(store_id):
    tables = Table.query.filter_by(store_id=store_id).order_by(Table.id).all()

    return render_template("tables/index.html", tables=tables, store_id=store_id)


@tables_bp.route('/store/<int:store_id>/table/new')
@check_login_in()
def new(store_id):
    return render_template("tables/new.html", store_id=store_id)


@tables_bp.route('/store/<int:store_id>/table/create', methods=['POST'])
@check_login_in()
def create(store_id):
    store = Store.query.get(store_id)

    name = request.form['name']

    table = Table(name=name, store=store)
    db.session.add(table)
    db.session.commit()

    return redirect(url_for('tables_bp.index', store_id=store_id))


@tables_bp.route('/table/<int:id>/edit')
@check_login_in()
def edit(id):
    table = Table.query.get(id)

    return render_template('tables/edit.html', table=table)


@tables_bp.route('/table/<int:id>/update', methods=['POST'])
@check_login_in()
def update(id):
    table = Table.query.get(id)

    table.name = request.form['name']
    db.session.commit()

    return redirect(url_for('tables_bp.index', store_id=table.store_id))


@tables_bp.route('/table/<int:id>/delete')
@check_login_in()
def delete(id):
    table = Table.query.get(id)
    store_id = table.store_id

    db.session.delete(table)
    db.session.commit()

    return redirect(url_for('tables_bp.index', store_id=store_id))


@tables_bp.route('/table/<int:id>/clear')
@check_login_in()
def clear(id):
    table = Table.query.get(id)

    table.status = TableState.NOT_ORDER
    db.session.commit()

    key_str = 'table' + str(id)
    if key_str in parameters.order_list:
        parameters.order_list[key_str] = {}

    return redirect(url_for('tables_bp.index', store_id=table.store_id))


app/templates/tables/edit.html
{% extends "base.html" %}

{% block body %}
<h1>編輯餐桌</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('tables_bp.update', id=table.id) }}">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ table.name }}"/>
    </div>

    <button type="submit" class="btn btn-primary">編輯</button>
  </form>
</div>
{% endblock %}

app/templates/tables/index.html
{% extends "header.html" %} 

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('stores_bp.index') }}">Stores</a></li>
          <li class="breadcrumb-item active" aria-current="page">Tables</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-12">
      <a href="{{ url_for('tables_bp.new', store_id=store_id) }}" class="btn btn-info">新增餐桌</a>
      <table class="table table-image">
        <thead>
          <tr>
            <th scope="col">桌號</th>
            <th scope="col">狀態</th>
            <th scope="col">清單</th>
            <th scope="col">編輯</th>
          </tr>
        </thead>
        <tbody>
          {% for table in tables %}
          <tr data-table-id="{{ table.id }}">
            <td scope="row">{{ table.name }}</td>
            <td scope="row" id="tableStatus">{{ table.status.value }}</td>
            <td scope="row">
              <a href="{{ url_for('orders_bp.new', table_id=table.id) }}" class="btn btn-info" role="button" aria-disabled="true" id="link">連結</a>
              <a href="{{ url_for('tables_bp.clear', id=table.id) }}" class="btn btn-danger disabled" role="button" aria-disabled="true" id="clear">清空</a>
            </td>
            <td>
              <a href="{{ url_for('tables_bp.edit', id=table.id) }}" class="btn btn-info">修改</a>
              <a href="{{ url_for('tables_bp.delete', id=table.id) }}" class="btn btn-danger" onclick="return confirm('確定刪除該餐桌？')">刪除</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="row mt-5">
        <div class="col-12">
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="https://cdn.socket.io/socket.io-3.0.1.min.js"></script>
<script type="module" src="{{ url_for('tables_bp.static', filename='js/order_list.js') }}"></script>
{% endblock %}

app/templates/tables/new.html
{% extends "base.html" %}

{% block body %}
<h1>新增餐桌</h1>

<div class="col-md-4">
  <form method="POST" action="{{ url_for('tables_bp.create', store_id=store_id) }}">
    <div class="form-group">
      <label for="name">名稱</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="name"/>
    </div>

    <button type="submit" class="btn btn-primary">新增</button>
  </form>
</div>
{% endblock %}